[package]
edition = "2024"
name = "amqdo"
version = "0.1.1"
authors = ["russell"]

[dependencies]
config = "0.9.3"
reqwest = "0.9.17"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
serde-xml-rs = "0.3.1"
