[package]
edition = "2024"
name = "amqdo"
version = "0.1.1"
authors = ["russell"]

[dependencies]
config = "0.15.14"
reqwest = { version = "0.12.23", features = ["blocking"] }
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
serde-xml-rs = "0.8.1"
